### ISSUE TITLE
Do we really need uikit images ?

### ISSUE THREAD

**Issue by trk** [uatrend/pagekit#21]
Do we really need these `app\system\modules\theme\image\*.*` files ?

https://github.com/uikit/uikit/blob/develop/src/less/components/mixin.less#L11 We have a method here for inline svg usage.

Also we can use custom uikit icons js file for Pagekit CMS.

For these kind of usages [#L98](https://github.com/uatrend/pagekit/blob/develop/app/system/modules/theme/less/theme.less#L98), [#L102](https://github.com/uatrend/pagekit/blob/develop/app/system/modules/theme/less/theme.less#L102), [#L105](https://github.com/uatrend/pagekit/blob/develop/app/system/modules/theme/less/theme.less#L105), [#L108](https://github.com/uatrend/pagekit/blob/develop/app/system/modules/theme/less/theme.less#L108), [#L111](https://github.com/uatrend/pagekit/blob/develop/app/system/modules/theme/less/theme.less#L111)

## Example:

`<span uk-icon="icon: pagekit-help; ratio: 2"></span>` for [#L98](https://github.com/uatrend/pagekit/blob/develop/app/system/modules/theme/less/theme.less#L98)

**Comment by uatrend** [comment]
Maybe, this icons the same, but they looks different. Default Pagekit icons more accurate. Maybe better would create own uikit-icons.js for pagekit? :)

**Comment by trk** [comment]
We can create a js file like `pagekit.icons.js` same content with `uikit.icons.js`, but we can add more custom svg icons after https://github.com/uikit/uikit/blob/develop/dist/js/uikit-icons.js#L156 line or all icons could be custom.

**Comment by uatrend** [comment]
:) Hi guys! Pagekit icons in last commit (https://github.com/uatrend/pagekit/commit/9340e92e5726d6a16922142a68c0d09d213edcdc) now in 'uikit-icons.js' placed  in /app/system/assets/js folder. Removed unused styles from less.
