### ISSUE TITLE
The installer is broken

### ISSUE THREAD

**Issue by jopsa** [uatrend/pagekit#22]
Hi, 

I cloned this repository and installed all dependencies but when go to url the installer is broken (white page) We need install another dependencies? Thank you

**Comment by uatrend** [comment]
Please check - install composer dependencies first.

**Comment by jopsa** [comment]
> 
> 
> Please check - install composer dependencies first.

Of course i did it, first 'install composer' and after 'npm install'

**Comment by uatrend** [comment]
Сan you show console errors?

**Comment by jopsa** [comment]
> 
> 
> Сan you show console errors?

Of course, look 3 images, i reinstalled composer and npm and how u can see ... 

![pk1](https://user-images.githubusercontent.com/3385024/67787041-7c789a00-fa35-11e9-82e3-be76e0d61a99.png)
![pk2](https://user-images.githubusercontent.com/3385024/67787047-7edaf400-fa35-11e9-9612-af981cb9e5c6.png)
![pk3](https://user-images.githubusercontent.com/3385024/67787052-813d4e00-fa35-11e9-80e2-f0d46cfbc445.png)

**Comment by uatrend** [comment]
Gulp script not started. Try exec in that dir - `$ node_modules/.bin/gulp` (without './')
Must be like...
<img width="780" alt="zsh" src="https://user-images.githubusercontent.com/24713453/67797388-7a4d2480-faa3-11e9-9de7-25094dd15f7c.png">

**Comment by jopsa** [comment]
I think that is windows problem, cuz i replaced "./node_modules/.bin/gulp" to "node_modules/.bin/gulp" and the console say some like this .. translated: '"node_modules" is not recognized as an internal or external command'

**Comment by uatrend** [comment]
If you can't start, install gulp globally.

**Comment by jopsa** [comment]
> 
> 
> If you can't start, install gulp globally.

Yes, my gulp was installed globally... Btw its work now the page installer. I replaced `"install": "./node_modules/.bin/webpack --progress --hide-modules -p && ./node_modules/.bin/gulp",` to `"install": "./node_modules/.bin/webpack --progress --hide-modules -p",` and add new line `"gulp":  "./node_modules/.bin/gulp",` so i exec `npm install` and after `npm run gulp` and is all... thanks
